export { chooseInitLetters } from './chooseInitLetters'
export { getLetter } from './getLetter'
export { getLetters } from './getLetters'
export { mapLetters } from './mapLetters'
export { mixLetters } from './mixLetters'
